import { SisterGreeting, ScrapbookTheme } from "./types";

export const THEME_OPTIONS: {
  id: ScrapbookTheme;
  name: string;
  desc: string;
  previewColor: string;
  bgClass: string;
  bannerImg?: string;
}[] = [
  {
    id: "chibi-anime",
    name: "Cute Chibi Sibling Anime",
    desc: "Warm sunset, pastel clouds, and adorable chibi sibling anime art (Style Ref 3)",
    previewColor: "#F59E0B",
    bgClass: "bg-chibi-pattern",
    bannerImg: "/assets/rakhi_chibi_anime.jpg",
  },
  {
    id: "mandala-anime",
    name: "Festive Mandala & Diya Vector",
    desc: "Circular gold mandala, marigold garlands, gifts, and modern vector art (Style Ref 1)",
    previewColor: "#D97706",
    bgClass: "bg-mandala-pattern",
    bannerImg: "/assets/rakhi_mandala_anime.jpg",
  },
  {
    id: "crimson-arch",
    name: "Royal Crimson Temple Arch",
    desc: "Rich maroon archway, glowing gold mandala, and Devanagari calligraphy (Style Ref 2)",
    previewColor: "#881337",
    bgClass: "bg-crimson-arch-pattern",
    bannerImg: "/assets/rakhi_crimson_arch.png",
  },
  {
    id: "dhaka-nepal",
    name: "Nepali Dhaka & Marigold",
    desc: "Authentic Nepali Dhaka geometric print, marigold saffron, and crimson tones",
    previewColor: "#991B1B",
    bgClass: "bg-dhaka-pattern",
  },
  {
    id: "gingham-red",
    name: "Classic Picnic Gingham",
    desc: "Timeless red-and-cream plaid scrapbook aesthetic",
    previewColor: "#DC2626",
    bgClass: "bg-gingham-red",
  },
  {
    id: "royal-patan",
    name: "Royal Patan & Gold",
    desc: "Regal temple gold and deep heritage blue border",
    previewColor: "#1E3A8A",
    bgClass: "bg-patan-pattern",
  },
  {
    id: "cherry-blossom",
    name: "Gulabi / Rose Bloom",
    desc: "Soft rose pastel and floral paper textures",
    previewColor: "#DB2777",
    bgClass: "bg-blossom-pattern",
  },
  {
    id: "himalayan-green",
    name: "Himalayan Pine & Kraft",
    desc: "Mountain greenery, rustic kraft paper, and pine notes",
    previewColor: "#047857",
    bgClass: "bg-himalaya-pattern",
  },
];

export const DEFAULT_NEPALI_LABELS = [
  {
    id: "label-1",
    title: "Momo & Khaja Raider",
    subtitle: "Says 'I am full' then eats 4 momos straight from my plate",
    emoji: "🥟",
    position: "top-left" as const,
  },
  {
    id: "label-2",
    title: "Personal eSewa / ATM",
    subtitle: "Calls sweetly only when her balance is exactly zero",
    emoji: "📱",
    position: "top-right" as const,
  },
  {
    id: "label-3",
    title: "Free Pathao & Driver",
    subtitle: "Thinks I am her 24/7 personal scooter cab service",
    emoji: "🛵",
    position: "left" as const,
  },
  {
    id: "label-4",
    title: "Ghar ko Supreme CCTV",
    subtitle: "Threatens 'Mummy lai bhandinchhu' every 5 minutes",
    emoji: "🚨",
    position: "right" as const,
  },
  {
    id: "label-5",
    title: "Drama Queen 3000",
    subtitle: "Cries at K-dramas, laughs at my misery",
    emoji: "🎭",
    position: "bottom-left" as const,
  },
  {
    id: "label-6",
    title: "Mero Mutu ko Tukra",
    subtitle: "The most annoying human, but my forever best friend",
    emoji: "❤️",
    position: "bottom-right" as const,
  },
];

export const DEFAULT_NEPALI_GIFTS = [
  {
    id: 1,
    title: "Gift Box #1",
    perk: "My Eternal Respect (100% Free & Tax-Free in Nepal)",
    emoji: "👑",
    color: "#B91C1C",
  },
  {
    id: 2,
    title: "Gift Box #2",
    perk: "1x TV Remote Pass (Valid for 1 YouTube/Netflix night)",
    emoji: "📺",
    color: "#D97706",
  },
  {
    id: 3,
    title: "Gift Box #3",
    perk: "रू. १० Dakshina (Don't spend it all at Bhatbhateni!)",
    emoji: "💵",
    color: "#059669",
  },
];

export const DEMO_SISTERS: SisterGreeting[] = [
  {
    id: "simran-khadka",
    sisterName: "Simran Khadka",
    nickname: "Simu / Chiku",
    brotherName: "Alok Poddar Baishya",
    heroPhoto: "/assets/rakhi_chibi_anime.jpg",
    rakhiPhoto: "/assets/rakhi_mandala_anime.jpg",
    certificatePhoto: "/assets/rakhi_chibi_anime.jpg",
    breakdownPhoto: "/assets/rakhi_crimson_arch.png",
    polaroids: [
      {
        id: "p1",
        photoUrl: "/assets/rakhi_chibi_anime.jpg",
        caption: "Cute chibi anime moments with my sister",
        date: "Childhood Anime Memories",
        rotation: -3,
      },
      {
        id: "p2",
        photoUrl: "/assets/rakhi_mandala_anime.jpg",
        caption: "Tying Rakhi with smiles & blessings",
        date: "Janai Purnima / Rakhi",
        rotation: 2,
      },
      {
        id: "p3",
        photoUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&fit=crop&q=80",
        caption: "Late night Momo & street food runs",
        date: "Kathmandu Shenanigans",
        rotation: -2,
      },
      {
        id: "p4",
        photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
        caption: "Always judging my driving and outfit",
        date: "Pokhara Road Trip",
        rotation: 3,
      },
    ],
    funnyLabels: DEFAULT_NEPALI_LABELS,
    gifts: [
      {
        id: 1,
        title: "Gift Box #1",
        perk: "Unlimited Momo Treat at Dalle / Bota (My treat!) 🥟",
        emoji: "🥟",
        color: "#B91C1C",
      },
      {
        id: 2,
        title: "Gift Box #2",
        perk: "1x TV & Music Remote Control Pass (No fighting today) 📺",
        emoji: "📺",
        color: "#D97706",
      },
      {
        id: 3,
        title: "Gift Box #3",
        perk: "रू. १० Dakshina (Don't spend it all at Bhatbhateni! 😉) 💵",
        emoji: "💵",
        color: "#059669",
      },
    ],
    certificate: {
      title: "Best Sister in Nepal Award",
      subtitle: "Presented to Simran Khadka for listening to all my 2 AM rants, tolerating my terrible jokes, and being the sweetest partner-in-crime.",
      date: "Raksha Bandhan 2024",
      signature: "Your Loving Brother, Alok Poddar Baishya",
      sealText: "OFFICIAL SIBLING SEAL • CERTIFIED IN NEPAL",
    },
    letter: {
      title: "To my favorite sister Simran,",
      paragraphs: [
        "Happy Raksha Bandhan, Simran! Even though you steal my hoodies, eat all the good snacks before I can even see them, and complain about my driving every single time, life would be dreadfully boring without you.",
        "Thank you for always having my back, giving the most honest advice, and keeping our sibling bond so lively and special.",
        "No matter how old we get or how much we argue over who gets the TV remote, remember that your brother Alok is always right by your side. Always proud of you!"
      ],
      signoff: "With endless love & sibling hugs,\nAlok Poddar Baishya ❤️",
      ps: "P.S. You still owe me रू ५०० from our last Swiggy/Bhoj order! 🛵",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    views: 120,
    theme: "chibi-anime",
    currencySymbol: "रू.",
  },
  {
    id: "bhawana-parsai",
    sisterName: "Bhawana Parsai",
    nickname: "Drama Queen / Chhuchhi",
    brotherName: "Alok Poddar Baishya",
    heroPhoto: "/assets/rakhi_mandala_anime.jpg",
    rakhiPhoto: "/assets/rakhi_chibi_anime.jpg",
    certificatePhoto: "/assets/rakhi_mandala_anime.jpg",
    breakdownPhoto: "/assets/rakhi_crimson_arch.png",
    polaroids: [
      {
        id: "bp1",
        photoUrl: "/assets/rakhi_mandala_anime.jpg",
        caption: "Mandala & Diya festive Rakhi celebration",
        date: "Festive Joy",
        rotation: -3,
      },
      {
        id: "bp2",
        photoUrl: "/assets/rakhi_chibi_anime.jpg",
        caption: "Practicing her Oscar-worthy crying face",
        date: "Every single day",
        rotation: 3,
      },
      {
        id: "bp3",
        photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
        caption: "Rare moment of peace before the fight begins",
        date: "Festive Morning",
        rotation: -2,
      },
      {
        id: "bp4",
        photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80",
        caption: "Waiting for her Dakshina like a boss",
        date: "Rakhi 2024",
        rotation: 2,
      },
    ],
    funnyLabels: DEFAULT_NEPALI_LABELS,
    gifts: [
      {
        id: 1,
        title: "Gift #1",
        perk: "1 Free Pass to Complain Without Me Making Fun of You",
        emoji: "🎫",
        color: "#B91C1C",
      },
      {
        id: 2,
        title: "Gift #2",
        perk: "24-Hour Immunity from Sibling Roasting & Pranks",
        emoji: "🛡️",
        color: "#D97706",
      },
      {
        id: 3,
        title: "Gift #3",
        perk: "Full Rights to Pick What We Watch Tonight on TV",
        emoji: "🍿",
        color: "#059669",
      },
    ],
    certificate: {
      title: "Gold Medal in Sibling Drama & Theatrics",
      subtitle: "Presented to Bhawana Parsai for being the most expressive, dramatic, yet undeniably beloved sister in Nepal.",
      date: "Janai Purnima / Raksha Bandhan",
      signature: "Your Loving Brother, Alok Poddar Baishya",
      sealText: "CERTIFIED SIBLING DRAMA QUEEN • OFFICIAL",
    },
    letter: {
      title: "To my favorite Bollywood actress at home, Bhawana,",
      paragraphs: [
        "Happy Rakhi Bhawana! There is honestly never a silent or boring second when you are around. You turn even a simple grocery trip into a full Bollywood cinematic experience!",
        "Thank you for being my constant partner in mischief and the person I trust most with all my secrets.",
        "May this Rakhi bring you endless happiness, good food, success in your goals, and cute outfits!"
      ],
      signoff: "Love always,\nAlok Poddar Baishya ❤️",
      ps: "P.S. Dakshina payepachi Selroti ra sweets share garnu parcha! 🥮",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    views: 95,
    theme: "mandala-anime",
    currencySymbol: "रू.",
  },
  {
    id: "shivangi-shah-karki",
    sisterName: "शिवाङ्गी शाह कार्की",
    nickname: "Mero Mutu / Shivu",
    brotherName: "Alok Poddar Baishya",
    heroPhoto: "/assets/rakhi_crimson_arch.png",
    rakhiPhoto: "/assets/rakhi_chibi_anime.jpg",
    certificatePhoto: "/assets/rakhi_crimson_arch.png",
    breakdownPhoto: "/assets/rakhi_mandala_anime.jpg",
    polaroids: [
      {
        id: "ssk1",
        photoUrl: "/assets/rakhi_crimson_arch.png",
        caption: "Happy रक्षाबंधन • Sacred Promise of Love",
        date: "Raksha Bandhan 2024",
        rotation: -4,
      },
      {
        id: "ssk2",
        photoUrl: "/assets/rakhi_chibi_anime.jpg",
        caption: "Forever cute chibi anime sibling vibes",
        date: "Sweet Memories",
        rotation: 3,
      },
      {
        id: "ssk3",
        photoUrl: "/assets/rakhi_mandala_anime.jpg",
        caption: "Tying Rakhi with traditional love & diya",
        date: "Janai Purnima Special",
        rotation: -2,
      },
      {
        id: "ssk4",
        photoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
        caption: "Queen of the household",
        date: "Memories",
        rotation: 2,
      },
    ],
    funnyLabels: DEFAULT_NEPALI_LABELS,
    gifts: [
      {
        id: 1,
        title: "Gift Box #1",
        perk: "Special Chocolate Box + Secret Momo Party 🍫🥟",
        emoji: "🎁",
        color: "#881337",
      },
      {
        id: 2,
        title: "Gift Box #2",
        perk: "Free Pathao / Scooter Ride whenever you call 🛵",
        emoji: "🛵",
        color: "#D97706",
      },
      {
        id: 3,
        title: "Gift Box #3",
        perk: "रू. ५०० Special Shagun / Dakshina on eSewa 💵",
        emoji: "💵",
        color: "#059669",
      },
    ],
    certificate: {
      title: "सर्वोत्कृष्ट बहिनी / दिदी सम्मान पत्र (Best Sister Award)",
      subtitle: "शिवाङ्गी शाह कार्कीलाई संसारकै सबैभन्दा प्यारी, चुलबुले र सधैं साथ दिने बहिनी भएकोमा यो विशेष सम्मान प्रदान गरिन्छ।",
      date: "रक्षाबन्धन / जनै पूर्णिमा २०८१",
      signature: "तपाईंको मायालु दाजु, Alok Poddar Baishya",
      sealText: "OFFICIAL SIBLING CERTIFICATE • 100% GENUINE",
    },
    letter: {
      title: "प्यारी शिवाङ्गी शाह कार्की (Shivu),",
      paragraphs: [
        "रक्षाबन्धन तथा जनै पूर्णिमाको धेरै धेरै शुभकामना! तिमी जस्तो मायालु, रमाइलो र सधैं मुहारमा हाँसो ल्याउने बहिनी पाउनु मेरो लागि ठूलो भाग्य हो।",
        "हामी जति झगडा गरे पनि, तिमी मेरो जीवनको सबैभन्दा अमूल्य मान्छे हौ। तिम्रो हरेक सपना पूरा होस् र सधैं यसरी नै खुसी रहनू।",
        "जस्तोसुकै अवस्थामा पनि तिम्रो दाजु Alok तिम्रो साथमा रहनेछ। सधैं माया र आशिर्वाद!"
      ],
      signoff: "धेरै धेरै माया सहित,\nदाजु Alok Poddar Baishya ❤️",
      ps: "P.S. दक्षिणा पाएपछि मलाई पनि मिठाइ खुवाउनु पर्छ है! 🥮",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    views: 168,
    theme: "crimson-arch",
    currencySymbol: "रू.",
  },
  {
    id: "aayusha-thapa",
    sisterName: "Aayusha Thapa",
    nickname: "Momo Raider / Chhuchhi",
    brotherName: "Alok Poddar Baishya",
    heroPhoto: "/assets/rakhi_chibi_anime.jpg",
    rakhiPhoto: "/assets/rakhi_mandala_anime.jpg",
    certificatePhoto: "/assets/rakhi_chibi_anime.jpg",
    breakdownPhoto: "/assets/rakhi_crimson_arch.png",
    polaroids: [
      {
        id: "at1",
        photoUrl: "/assets/rakhi_chibi_anime.jpg",
        caption: "Partners in mischief since forever",
        date: "Childhood Days",
        rotation: -3,
      },
      {
        id: "at2",
        photoUrl: "/assets/rakhi_mandala_anime.jpg",
        caption: "Momo eating competitions at 2 AM",
        date: "Kathmandu Foodies",
        rotation: 2,
      },
      {
        id: "at3",
        photoUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&fit=crop&q=80",
        caption: "Pretending to be mature adults for 5 mins",
        date: "Dashain Special",
        rotation: -2,
      },
      {
        id: "at4",
        photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
        caption: "The Queen of household drama",
        date: "Home Memories",
        rotation: 3,
      },
    ],
    funnyLabels: DEFAULT_NEPALI_LABELS,
    gifts: [
      {
        id: 1,
        title: "Gift #1",
        perk: "1 Free Pass to steal my hoodie without me complaining 🧥",
        emoji: "🧥",
        color: "#B91C1C",
      },
      {
        id: 2,
        title: "Gift #2",
        perk: "Unlimited Momo plate sharing rights 🥟",
        emoji: "🥟",
        color: "#D97706",
      },
      {
        id: 3,
        title: "Gift #3",
        perk: "रू. १०० Dakshina for emergency snacks 💵",
        emoji: "💵",
        color: "#059669",
      },
    ],
    certificate: {
      title: "Best Little Sister in Nepal Award",
      subtitle: "Presented to Aayusha Thapa for being the most energetic, funny, and precious sister anyone could ever have.",
      date: "Raksha Bandhan / Janai Purnima",
      signature: "Your Brother, Alok Poddar Baishya",
      sealText: "OFFICIAL SIBLING SEAL • 100% GENUINE",
    },
    letter: {
      title: "To my dear sister Aayusha,",
      paragraphs: [
        "Happy Raksha Bandhan Aayusha! Even though you eat my share of snacks and complain about everything, home is never dull with you.",
        "Thank you for being my constant cheerleader and keeping our sibling bond so special.",
        "May this festive season bring you endless happiness, good health, and sweet treats!"
      ],
      signoff: "Love always,\nAlok Poddar Baishya ❤️",
      ps: "P.S. Don't forget to share your Dakshina! 🍫",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    views: 74,
    theme: "dhaka-nepal",
    currencySymbol: "रू.",
  },
];
